// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzZOnZArHi5BXDvjmgU_egSQKf72ITRQ0',
    appId: '1:934922922503:android:db051a1a427dcd45c8d8a2',
    messagingSenderId: '934922922503',
    projectId: 'guida-a3f67',
    storageBucket: 'guida-a3f67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zKhO0GXE-sALs0fplT3I6Dkj7EGJkss',
    appId: '1:934922922503:ios:9e01807d5878b980c8d8a2',
    messagingSenderId: '934922922503',
    projectId: 'guida-a3f67',
    storageBucket: 'guida-a3f67.appspot.com',
    iosBundleId: 'com.tmdc.guida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9zKhO0GXE-sALs0fplT3I6Dkj7EGJkss',
    appId: '1:934922922503:ios:9e01807d5878b980c8d8a2',
    messagingSenderId: '934922922503',
    projectId: 'guida-a3f67',
    storageBucket: 'guida-a3f67.appspot.com',
    iosBundleId: 'com.tmdc.guida',
  );

}